name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run tests
      run: sbt clean coverage test coverageReport coverageAggregate
    - name: Show target files
      run: ls ./target/scala-2.12
    - name: Print scoverage file
      run: cat target/scala-2.12/scoverage-report/scoverage.xml
    - name: Grep /home/runner/work/
      run: grep "/home/runner/work/" target/scala-2.12/scoverage-report/scoverage.xml
      
    - name: Replace from /home/runner/work/scala-test-coverage-sonar-cloud/scala-test-coverage-sonar-cloud/ to /github/workspace
      run: sed -i 's#/home/runner/work/scala-test-coverage-sonar-cloud/scala-test-coverage-sonar-cloud#/github/workspace#g' target/scala-2.12/scoverage-report/scoverage.xml
      
    - name: Grep /home/runner/work/
      run: grep "/github/workspace/" target/scala-2.12/scoverage-report/scoverage.xml
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
